name: Test (PR)

on: [pull_request]
env:
  BUILD: false
jobs:
  test:
    name: Test

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [linux-stable, macos-stable, windows-stable]
        include:
          - build: linux-stable
            os: ubuntu-latest
            rust: stable
          - build: macos-stable
            os: macos-latest
            rust: stable
          - build: windows-stable
            os: windows-latest
            rust: stable

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Setup environment
        run: |
          chmod +x ci/buildvars.sh
          ci/buildvars.sh

      - name: Install Rust
        run: |
          rustup update ${{ matrix.rust }} --no-self-update
          rustup default ${{ matrix.rust }}
        if: env.BUILD == 'true'
      - name: Install perl modules
        uses: perl-actions/install-with-cpanm@v1
        with:
          install: "HTML::Entities"
      - name: Run Tests
        run: make test
        env:
          RUST_BACKTRACE: 1
